version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing Docker..."

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t coworking .

  post_build:
    commands:
      - echo "Tagging the Docker image..."
      - docker tag coworking:latest 384232680670.dkr.ecr.eu-central-1.amazonaws.com/coworking:latest
      - echo "Pushing the Docker image to AWS ECR..."
      - docker push 384232680670.dkr.ecr.eu-central-1.amazonaws.com/coworking:latest
      - echo "Build completed on `date`"

