version: 0.2

phases:
pre_build:
  commands:
    - echo "Logging in to Amazon ECR..."
    - echo $(aws ecr get-login-password --region eu-central-1) | docker login --username AWS --password-stdin 384232680670.dkr.ecr.eu-central-1.amazonaws.com


  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t coworking:latest .
      - docker tag coworking:latest 384232680670.dkr.ecr.eu-central-1.amazonaws.com/coworking:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to AWS ECR..."
      - docker push 384232680670.dkr.ecr.eu-central-1.amazonaws.com/coworking:latest
      - echo "Build completed on `date`"
